run:
  timeout: 5m
  tests: true

output:
    sort-results: true

linters:
  enable-all: true
  disable:
    # deprecated
    - forbidigo
    - scopelint
    - maligned
    - varcheck
    - structcheck
    - interfacer
    - exhaustivestruct
    - golint
    - nosnakecase
    - deadcode
    - ifshort
