// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Connect(arg1:string):Promise<void>;

export function Connected():Promise<boolean>;

export function Domains():Promise<Array<domain.Domain>>;
