// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Domains():Promise<Array<domain.Domain>>;

export function Greet(arg1:string):Promise<string>;
