// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function Domains() {
  return window['go']['app']['App']['Domains']();
}
