// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function Connected() {
  return window['go']['app']['App']['Connected']();
}

export function Destroy(arg1) {
  return window['go']['app']['App']['Destroy'](arg1);
}

export function Domains() {
  return window['go']['app']['App']['Domains']();
}

export function Resume(arg1) {
  return window['go']['app']['App']['Resume'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function Start(arg1) {
  return window['go']['app']['App']['Start'](arg1);
}

export function Suspend(arg1) {
  return window['go']['app']['App']['Suspend'](arg1);
}
