name: virt-manager CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Go version
        run: go version

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint

      - name: Lint
        run: make lint
        
  build:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails

      - name: Wails version
        run: wails version

      - name: Build
        run: make build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: make test
